In [1]:
import pandas as pd
import re 
import numpy as np

df=pd.read_csv("../my-code/dffinal.csv")

In [2]:
display(df)

,Period,Country,Area,Type,Fatal (Y/N),Time
0,1997-2016,AUSTRALIA,Victoria,Unprovoked,N,Morning
1,1937-1956,AUSTRALIA,South Australia,Provoked,Unknown,Unspecified
2,1937-1956,AUSTRALIA,New South Wales,Unprovoked,Y,Afternoon
3,1997-2016,AUSTRALIA,New South Wales,Unprovoked,N,Morning
4,1997-2016,AUSTRALIA,New South Wales,Unspecified,Y,Unspecified
...,...,...,...,...,...,...
3743,1997-2016,USA,Florida,Unprovoked,N,Afternoon
3744,1997-2016,USA,Virginia,Unspecified,N,Unspecified
3745,1997-2016,USA,Florida,Provoked,N,Morning
3746,1997-2016,USA,Florida,Unprovoked,N,Afternoon
3747,1916-1936,USA,North Carolina,Unprovoked,N,Unspecified